---
apiVersion: apps/v1
kind: Deployment #Kubernetes resource we are creating
metadata:
  name: mvnwebapp
spec:
  selector:
    matchLabels:
      app: mvnwebapp
  replicas: 2 #No of replica that will be created for mvnwebapp-k8s
  template:
   metadata:
    labels:
     app: mvnwebapp
  spec:
    containers:
      - name: mvnwebapp
        image: vinitpania/mvnwebapp #This image is used
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 9594 #this port is used
           

---

apiVersion: v1
kind: Service
metadata:
  name: mvnwebapp
spec:
  selector:
    app: mvnwebapp
  ports:
    - port: 9594
      protocol: "TCP"
      targetPort: 9594
  type: NodePort
    